services:
    create_task_command_handler:
        class: Domain\Task\Handler\CreateTaskCommandHandler
        arguments: [@task_repository]
        tags:
            - { name: command_handler, handles: Domain\Task\Command\CreateTask }

    delete_task_command_handler:
        class: Domain\Task\Handler\DeleteTaskCommandHandler
        arguments: [@task_repository]
        tags:
            - { name: command_handler, handles: Domain\Task\Command\DeleteTask }

    get_task_command_handler:
        class: Domain\Task\Handler\GetTaskCommandHandler
        arguments: [@task_repository]
        tags:
            - { name: command_handler, handles: Domain\Task\Command\GetTask }

    get_tasks_by_user_command_handler:
        class: Domain\Task\Handler\GetTasksByUserCommandHandler
        arguments: [@task_repository]
        tags:
            - { name: command_handler, handles: Domain\Task\Command\GetTasksByUser }
