services:
    user_repository:
        alias: user_repository.doctrine

    user_repository.doctrine:
        class: UserBundle\Repository\DoctrineUserRepository
        factory: ["@doctrine", getRepository]
        arguments: ['Domain\User\Entity\User']
        public: false

    user_repository.in_memory:
        class: UserBundle\Repository\InMemoryUserRepository
        public: false
