parameters:
    lexik_jwt_authentication.security.authentication.entry_point.class: UserBundle\Security\Http\Authentication\JWTEntryPoint
    password_encoder_cost: %security_encoder_cost%

services:
    authentication.handler.authentication_failure:
        class: UserBundle\Security\Http\Authentication\AuthenticationFailureHandler
        tags:
            - { name: monolog.logger, channel: security }

    password_encoder:
        class: Domain\User\Security\PasswordEncoder
        arguments: ["%password_encoder_cost%"]

    user_provider:
        class: UserBundle\Security\SymfonyUserProvider
        arguments: [@user_repository]

    validator.unique.user_email:
        class: AppBundle\Validation\Constraints\UniqueFieldValidator
        arguments: [@user_repository]
        tags:
            - { name: validator.constraint_validator, alias: validator.unique.user_email }
