Domain\Task\Entity\Task:
    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order:
        - id
        - name
        - date
        - description
        - estimate
        - isCompleted
        - completedAt
        - timeSpent
        - important
        - createdAt
    properties:
        id:
            expose: true
            inline: true
            type: Domain\Task\Value\TaskId
        name:
            expose: true
            inline: true
            type: Domain\Task\Value\TaskName
        description:
            expose: true
            inline: true
            type: Domain\Core\Value\Description
        date:
            expose: true
            type: "DateTime<'Y-m-d'>"
        estimate:
            expose: true
            inline: true
            type: Domain\Task\Value\Estimate
        completedAt:
            expose: true
            serialized_name: completed_at
        timeSpent:
            expose: true
            inline: true
            type: Domain\Task\Value\TimeSpent
        important:
            expose: true
            serialized_name: important
            type: boolean
        createdAt:
            expose: true
            serialized_name: created_at
    virtual_properties:
        isCompleted:
            serialized_name: completed
            type: boolean
