Domain\Task\Entity\Task:
    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order:
        - id
        - name
        - date
        - description
        - estimated
        - isCompleted
        - completedAt
        - timeSpent
        - important
        - createdAt
    properties:
        id:
            expose: true
            inline: true
            type: Domain\Task\ValueObject\TaskId
        name:
            expose: true
            inline: true
            type: Domain\Task\ValueObject\TaskName
        description:
            expose: true
            inline: true
            type: Domain\Core\ValueObject\Description
        date:
            expose: true
        estimated:
            expose: true
            inline: true
            type: Domain\Task\ValueObject\Estimated
        completedAt:
            expose: true
            serialized_name: completed_at
        timeSpent:
            expose: true
            inline: true
            type: Domain\Task\ValueObject\TimeSpent
        important:
            expose: true
            serialized_name: important
            type: boolean
        createdAt:
            expose: true
            serialized_name: created_at
    virtual_properties:
        isCompleted:
            serialized_name: completed
            type: boolean
