Domain\Task\ValueObject\TimeSpent:
    exclusion_policy: ALL
    properties:
        value:
            expose: true
            serialized_name: time_spent
            access_type: public_method
            access:
                getter: getValue
            read_only: true
