Domain\Task\ValueObject\Estimated:
    exclusion_policy: ALL
    properties:
        value:
            expose: true
            serialized_name: estimated
            access_type: public_method
            access:
                getter: getValue
            read_only: true
