Domain\Task\Command\CreateTask:
    properties:
        name:
            - NotBlank:
                message: Task name is required
            - Length:
                max: 1028
                maxMessage: Task name must be less than {{ limit }} characters
        date:
            - NotBlank:
                message: Date is required
            - Date:
                message: Date is not valid
        estimated:
            - Range:
                min: 0
                minMessage: Estimated must be a positive number
        done:
            - Type:
                type: bool
                message: Done is not a valid {{ type }}
        time_spent:
            - Range:
                min: 0
                minMessage: Time spent must be a positive number
