Domain\User\Entity\User:
    type: entity
    table: user
    repositoryClass: UserBundle\Repository\DoctrineUserRepository
    id:
        id:
            type: userid
            generator:
                strategy: NONE
    embedded:
        email:
            class: Domain\User\Value\Email
            columnPrefix: false
        fullName:
            class: Domain\User\Value\FullName
            columnPrefix: false
        password:
            class: Domain\User\Value\PasswordHash
            columnPrefix: false
    fields:
        createdAt:
            type: datetime
            column: created_at
