imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: middleware.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging:  "%kernel.debug%"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            taskid: TaskBundle\DBAL\Type\TaskIdType
            userid: UserBundle\DBAL\Type\UserIdType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                mappings:
                    core_embeddables:
                        mapping: true
                        type: yml
                        dir: "%kernel.root_dir%/../src/AppBundle/Resources/config/embeddable-mappings"
                        prefix: Domain\Core\ValueObject
                        is_bundle: false
                    task_models:
                        alias: Task
                        mapping: true
                        type: yml
                        dir: "%kernel.root_dir%/../src/TaskBundle/Resources/config/entity-mappings"
                        prefix: Domain\Task\Entity
                        is_bundle: false
                    task_embeddables:
                        mapping: true
                        type: yml
                        dir: "%kernel.root_dir%/../src/TaskBundle/Resources/config/embeddable-mappings"
                        prefix: Domain\Task\ValueObject
                        is_bundle: false
                    user_models:
                        alias: User
                        mapping:   true
                        type:      yml
                        dir:       "%kernel.root_dir%/../src/UserBundle/Resources/config/entity-mappings"
                        prefix:    Domain\User\Entity
                        is_bundle: false
                    user_embeddables:
                        mapping:   true
                        type:      yml
                        dir:       "%kernel.root_dir%/../src/UserBundle/Resources/config/embeddable-mappings"
                        prefix:    Domain\User\ValueObject
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener: ~
    disable_csrf_role: ROLE_API
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: force
        formats:
            json: true
    service:
        serializer: jms_serializer.serializer
    serializer:
        serialize_null: true
    exception:
        # The order is important!
        codes:
            Domain\Core\Exception\AssertionFailedException: 400
            Domain\Core\Exception\EntityNotFoundException: 404
            Domain\User\Exception\AccessDeniedException: 403
            Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
            Domain\Core\Exception\DomainException: 400
        messages:
            Domain\Core\Exception\AssertionFailedException: true
            Domain\Core\Exception\EntityNotFoundException: true
            Domain\User\Exception\AccessDeniedException: true
            Symfony\Component\Security\Core\Exception\AccessDeniedException: true
            Domain\Core\Exception\DomainException: true

sensio_framework_extra:
    view: { annotations: false }

jms_serializer:
    metadata:
        directories:
            Core:
                namespace_prefix: Domain\Core
                path: "@AppBundle/Resources/config/serializer/"
            Task:
                namespace_prefix: Domain\Task
                path: "@TaskBundle/Resources/config/serializer/"
            User:
                namespace_prefix: Domain\User
                path: "@UserBundle/Resources/config/serializer/"

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path: %jwt_public_key_path%
    pass_phrase: %jwt_key_pass_phrase%
    token_ttl: %jwt_token_ttl%
