services:
    signup_command_handler:
        class: Domain\User\Handler\SignUpCommandHandler
        arguments: [@user_repository, @password_encoder]
        tags:
            - { name: command_handler, handles: Domain\User\Command\SignUp }

    command_validator_middleware:
        class: AppBundle\Middleware\CommandValidatorMiddleware
        arguments: [@command_validator]
        public: false
        tags:
            - { name: command_bus_middleware }
