user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

task:
    resource: "@TaskBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
