app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api.user_all:
    path: /users
    defaults: { _controller: AppBundle:User:all }
    methods: [GET]

api.sign_up:
    path: /users
    defaults: { _controller: AppBundle:User:signUp }
    methods: POST
