# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    password_encoder_cost: 14

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form.error_extractor:
        class: AppBundle\Form\FlattenedFormErrorExtractor

    command_validator:
        class: AppBundle\Validation\Validator
        arguments: [@validator]

    password_encoder:
        class: Domain\User\Security\PasswordEncoder
        arguments: ["%password_encoder_cost%"]
