# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    user_repository:
        alias: user_repository.in_memory

    user_repository.in_memory:
        class: AppBundle\Repository\InMemoryUserRepository
        public: false
