# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    form.error_extractor:
        class: AppBundle\Form\FlattenedFormErrorExtractor

    command_validator:
        class: AppBundle\Validation\Validator
        arguments: [@validator]

    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
