Domain\User\ValueObject\PasswordHash:
    type: embeddable
    fields:
        value:
            type: string
            length: 60
            column: password
            options:
                fixed: true
