Domain\User\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            inline: true
            type: Domain\User\ValueObject\UserId
        email:
            expose: true
            inline: true
        fullName:
            expose: true
            inline: true
