Domain\User\ValueObject\Email:
    exclusion_policy: ALL
    properties:
        value:
            expose: true
            serialized_name: email
            access_type: public_method
            accessor:
                getter: getValue
            read_only: true
