Domain\User\Value\FullName:
    exclusion_policy: ALL
    properties:
        value:
            expose: true
            serialized_name: full_name
            access_type: public_method
            accessor:
                getter: getValue
            read_only: true
