Domain\Task\Entity\Task:
    type: entity
    table: task
    repositoryClass: TaskBundle\Repository\DoctrineTaskRepository
    id:
        id:
            type: taskid
            generator:
                strategy: NONE
    embedded:
        name:
            class: Domain\Task\ValueObject\TaskName
            columnPrefix: false
        description:
            class: Domain\Core\ValueObject\Description
            columnPrefix: false
        estimate:
            class: Domain\Task\ValueObject\Estimate
            columnPrefix: false
        timeSpent:
            class: Domain\Task\ValueObject\TimeSpent
            columnPrefix: false
    fields:
        date:
            type: date
            column: date
        completedAt:
            type: datetime
            column: completed_at
            nullable: true
            options:
                default: null
        important:
            type: boolean
            column: important
            options:
                default: 1
        createdAt:
            type: datetime
            column: created_at
    manyToOne:
        user:
            targetEntity: Domain\User\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
