Domain\User\Command\SignUp:
    properties:
        email:
            - NotBlank:
                message: The email is required
            - Email:
                message: The {{ value }} is not a valid email
        fullName:
            - NotBlank:
                message: The full name is required
        password:
            - NotBlank:
                message: The password is required
            - Length:
                min: 8
                max: 72
                minMessage: Password must be at least {{ limit }} characters
                maxMessage: Password must be less than {{ limit }} characters
