Domain\User\Command\SignUp:
    properties:
        email:
            - NotBlank:
                message: The email is required
            - Email:
                message: The {{ value }} is not a valid email
        fullName:
            - NotBlank:
                message: The full name is required
