Domain\Task\Value\Estimate:
    type: embeddable
    fields:
        value:
            type: smallint
            column: estimate
            options:
                unsigned: true
                default: 1
