Domain\Task\Value\TimeSpent:
    type: embeddable
    fields:
        value:
            type: smallint
            column: time_spent
            options:
                unsigned: true
                default: 0
